### ISSUE TITLE
Unable to run via Gatsby in macOS

### ISSUE THREAD

**Issue by cassiel** [jamesporter/solandra#27]
Getting this. (All works fine on Ubuntu.)

  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/nick/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/nick/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.

**Comment by jamesporter** [comment]
I have had loads of problems with the sharp (image dependency) on various versions of Gatsby/Node etc.

Have made two separate attempts to update the dependencies to address this, neither of which worked consistently.

But I think the underlying issues with the gatsby plugin dependency has now been addressed so I'll probably be able to fix reliably soon.

**Comment by cassiel** [comment]
Thanks. I'm happy to work with the Ubuntu/Debian system for the time being.

Much as I'm intrigued by Gatsby (it's new to me), what would also be useful is a way to crank out a raw, non-modulised version of Solandra that can be dropped straight into a web page and used without any further machinery. I want to try programming it via ClojureScript, and I can't see a way to do that with Gatsby in the picture. Does "gatsby build" make anything which can be used in isolation?

**Comment by jamesporter** [comment]
I updated the dependencies  in #28 (it now seems to build fine, after deleting node_modules on Cataline/node 13 and Netlify and github actions CI. 

`brew install vips` may help on Mac. 

But have had loads of issues with this dependency and node versions so not really convinced issue is addressed. Seems very sensitive to versions of dependencies.

On builds have have a look at the package.json

Not doing anything terribly fancy, really just using tsc (typescript compiler).

I think you should be able to set that up to produce what you want. I've intentionally set it up to do something that works well for modern ts/js projects; but https://stackoverflow.com/questions/34474651/typescript-compile-to-single-file will probably give you the options for something standalone.

Would be interested to hear how it goes with ClojureScript. A lot of solandra is designed around using typescript, with a lot of use of types and optional arguments.

**Comment by cassiel** [comment]
Thanks - I will give it a spin. I share your reservations about Quil - I personally find it too procedural and difficult to drop into other frameworks (I use it as a texture generator for THREE.js). If TypeScript transpiling is essentially type erasure then ClojureScript cross-calling should work fine.
